# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/zkservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/zkservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/zkservice.proto\x12\tzkservice\"\x90\x01\n\x10InferenceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fonnx_model_path\x18\x02 \x01(\t\x12\x17\n\x0finput_data_path\x18\x03 \x01(\t\x12\x12\n\nsplit_mode\x18\x04 \x01(\t\x12\x15\n\rops_per_chunk\x18\x05 \x01(\x05\x12\x11\n\tscheduler\x18\x06 \x01(\t\")\n\x13InferenceRequestAck\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\"\n\rWorkerRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"r\n\rJobAssignment\x12\x15\n\rjob_available\x18\x01 \x01(\x08\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x12\n\nmodel_path\x18\x04 \x01(\t\x12\x12\n\ninput_path\x18\x05 \x01(\t\"\x8d\x01\n\tJobResult\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\r\n\x05proof\x18\x04 \x01(\x0c\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x19\n\x11perf_metrics_json\x18\x07 \x01(\t\"\x17\n\tStatusAck\x12\n\n\x02ok\x18\x01 \x01(\x08\"j\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x1f\n\x0cHeartbeatAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xad\x02\n\x0cZKJobService\x12U\n\x16SubmitInferenceRequest\x12\x1b.zkservice.InferenceRequest\x1a\x1e.zkservice.InferenceRequestAck\x12@\n\nGetNextJob\x12\x18.zkservice.WorkerRequest\x1a\x18.zkservice.JobAssignment\x12=\n\x0fSubmitJobResult\x12\x14.zkservice.JobResult\x1a\x14.zkservice.StatusAck\x12\x45\n\rSendHeartbeat\x12\x1b.zkservice.HeartbeatRequest\x1a\x17.zkservice.HeartbeatAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.zkservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=37
  _globals['_INFERENCEREQUEST']._serialized_end=181
  _globals['_INFERENCEREQUESTACK']._serialized_start=183
  _globals['_INFERENCEREQUESTACK']._serialized_end=224
  _globals['_WORKERREQUEST']._serialized_start=226
  _globals['_WORKERREQUEST']._serialized_end=260
  _globals['_JOBASSIGNMENT']._serialized_start=262
  _globals['_JOBASSIGNMENT']._serialized_end=376
  _globals['_JOBRESULT']._serialized_start=379
  _globals['_JOBRESULT']._serialized_end=520
  _globals['_STATUSACK']._serialized_start=522
  _globals['_STATUSACK']._serialized_end=545
  _globals['_HEARTBEATREQUEST']._serialized_start=547
  _globals['_HEARTBEATREQUEST']._serialized_end=653
  _globals['_HEARTBEATACK']._serialized_start=655
  _globals['_HEARTBEATACK']._serialized_end=686
  _globals['_ZKJOBSERVICE']._serialized_start=689
  _globals['_ZKJOBSERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
