name: mnist_classifier
onnx_file: examples/onnx/mnist_classifier/network.onnx
input_file: examples/onnx/mnist_classifier/input.json
# split_mode: "none"  # options: "none", "auto", or "fixed"
split_mode: "none"       # options: "none", "auto", "fixed"
ops_per_chunk: 1         # used only if split_mode == "fixed"
schedule: "lpt"  # options: "fifo", "lpt" (longest processing time first)



# split_group_size: null #when null there is no model spltting
# group_splits: null # [[26,27]] #[[98,99],[97,98,99]] #null # [[1,2,3]] # [[1,3,5], [2,4,6], [7,8,9,10]]  # [[1,3,5], [2,4,6], [7,8,9,10]]

# examples/onnx/mnist_classifier