name: tiny_bert_split_size_1
onnx_file: examples/onnx/bert/bert_tiny.onnx
input_file: examples/onnx/bert/bert_tiny_input.json
# split_mode: "none"  # options: "none", "auto", or "fixed"
split_mode: "fixed"       # options: "none", "auto", "fixed"
ops_per_chunk: 1         # used only if split_mode == "fixed"
schedule: "fifo"  # options: "fifo", "lpt" (longest processing time first)