# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zkpservice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10zkpservice.proto\"2\n\tProofInfo\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x11\n\tdata_path\x18\x02 \x01(\x08\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\" \n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2s\n\x06Worker\x12\x1d\n\x0bProcessTask\x12\x05.Task\x1a\x05.Task\"\x00\x12\"\n\x04Ping\x12\x08.Message\x1a\x10.MessageResponse\x12&\n\x0c\x43omputeProof\x12\n.ProofInfo\x1a\x08.Message\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkpservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROOFINFO']._serialized_start=20
  _globals['_PROOFINFO']._serialized_end=70
  _globals['_MESSAGE']._serialized_start=72
  _globals['_MESSAGE']._serialized_end=98
  _globals['_MESSAGERESPONSE']._serialized_start=100
  _globals['_MESSAGERESPONSE']._serialized_end=152
  _globals['_TASK']._serialized_start=154
  _globals['_TASK']._serialized_end=186
  _globals['_WORKER']._serialized_start=188
  _globals['_WORKER']._serialized_end=303
# @@protoc_insertion_point(module_scope)
