# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zkpservice.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10zkpservice.proto\x12\nzkpservice\"c\n\x0cProofRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nonnx_model\x18\x02 \x01(\x0c\x12\x12\n\ninput_data\x18\x03 \x01(\t\x12\x19\n\x11\x63\x61\x63he_setup_files\x18\x04 \x01(\x08\"(\n\x12ProofStatusRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"`\n\x13ProofStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05proof\x18\x02 \x01(\x0c\x12\x18\n\x10performance_data\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"4\n\rProofResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xe6\x01\n\x10ZKPWorkerService\x12\x43\n\x0c\x43omputeProof\x12\x18.zkpservice.ProofRequest\x1a\x19.zkpservice.ProofResponse\x12\x38\n\x04Ping\x12\x13.zkpservice.Message\x1a\x1b.zkpservice.MessageResponse\x12S\n\x10\x43heckProofStatus\x12\x1e.zkpservice.ProofStatusRequest\x1a\x1f.zkpservice.ProofStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkpservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROOFREQUEST']._serialized_start=32
  _globals['_PROOFREQUEST']._serialized_end=131
  _globals['_PROOFSTATUSREQUEST']._serialized_start=133
  _globals['_PROOFSTATUSREQUEST']._serialized_end=173
  _globals['_PROOFSTATUSRESPONSE']._serialized_start=175
  _globals['_PROOFSTATUSRESPONSE']._serialized_end=271
  _globals['_PROOFRESPONSE']._serialized_start=273
  _globals['_PROOFRESPONSE']._serialized_end=325
  _globals['_MESSAGE']._serialized_start=327
  _globals['_MESSAGE']._serialized_end=353
  _globals['_MESSAGERESPONSE']._serialized_start=355
  _globals['_MESSAGERESPONSE']._serialized_end=407
  _globals['_ZKPWORKERSERVICE']._serialized_start=410
  _globals['_ZKPWORKERSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
