defaults:
  - _self_
  - model: mobilenet_split_size_1  # mobilenet, mnist_gan, mnist_classifier, little_transformer, nano_gpt
  # - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
cache_setup_files: True


hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging