defaults:
  - _self_
  - model: nano_gpt_4_layers_64_embd  # mobilenet, mnist_gan, mnist_classifier, little_transformer, nano_gpt
  # - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

worker_addresses: ["10.0.19.201:50051"]  # ["localhost:50052"]
cache_setup_files: False
spot_test: False
save_ezkl_settings: True
generate_ezkl_settings_only: False
hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging

#nano_gpt_4_layers_64_embd
#nano_gpt_4_layers_80_embd
#nano_gpt_4_layers_96_embd

#nano_gpt_4_layers_112_embd
#nano_gpt_4_layers_128_embd
#nano_gpt_4_layers_144_embd
#nano_gpt_5_layers_64_embd
#nano_gpt_10_layers_64_embd
#nano_gpt_15_layers_64_embd
#nano_gpt_20_layers_64_embd
#nano_gpt_25_layers_64_embd