defaults:
  - _self_
  - dispatcher: default
  - worker: default
  - model: mobilenetv2_split_size_1_fifo  

    #mobilenetv2_split_size_1_lpt
    #mobilenetv2_split_size_1_fifo
    #gpt_4_lay_64_emb_split_size_1_fifo
    # Options: mobilenetv2_050_Opset18, mnist_gan, little_transformer, nano_gpt, mnist_classifier, nano_gpt_4_layers_64_embd
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Global control flags
data_exchange_backend: local  # s3 or local. S3 needed for distributed mode. 
s3_bucket: dzkml   # S3 bucket for distributed data exchange/caching; set to null for single-machine/local cache.

# Cache control
cache_backend: local       # 'local' = disk cache (single machine), 's3' = object store (for distributed workers).
cache_setup: true          # If true, preserve cache files created during setup after the run. If false, remove cache files after the run.
overwrite_cache: false     # If true, always overwrite (regenerate) cached files. If false, reuse any existing cache files if present.

# Dispatcher or worker launch mode (set in CLI)
run_mode: null  # Options: dispatcher, worker, submit

# Hydra output control
hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging

#Launch Dispatcher
#python grpc_api/dispatcher_server.py --config-name=config run_mode=dispatcher

# Launch Worker:
#python grpc_api/worker_client.py --config-name=config run_mode=worker

#submit job to dispatcher
# python grpc_api/submit_job.py --config-name=config run_mode=submit