# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import zkservice_pb2 as zkservice__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zkservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZKJobServiceStub(object):
    """===== SERVICE =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGlobalJob = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitGlobalJob',
                request_serializer=zkservice__pb2.GlobalJobRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobIDResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/zkservice.ZKJobService/GetJobStatus',
                request_serializer=zkservice__pb2.JobIDRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.GetJobSummary = channel.unary_unary(
                '/zkservice.ZKJobService/GetJobSummary',
                request_serializer=zkservice__pb2.JobIDRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobSummaryResponse.FromString,
                _registered_method=True)
        self.FetchNextSubJob = channel.unary_unary(
                '/zkservice.ZKJobService/FetchNextSubJob',
                request_serializer=zkservice__pb2.WorkerIDRequest.SerializeToString,
                response_deserializer=zkservice__pb2.SubJobResponse.FromString,
                _registered_method=True)
        self.SubmitSubJobResult = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitSubJobResult',
                request_serializer=zkservice__pb2.SubJobResult.SerializeToString,
                response_deserializer=zkservice__pb2.StatusAck.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/zkservice.ZKJobService/SendHeartbeat',
                request_serializer=zkservice__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=zkservice__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.ListActiveSubJobs = channel.unary_unary(
                '/zkservice.ZKJobService/ListActiveSubJobs',
                request_serializer=zkservice__pb2.StatusAck.SerializeToString,
                response_deserializer=zkservice__pb2.SubJobStatusResponse.FromString,
                _registered_method=True)


class ZKJobServiceServicer(object):
    """===== SERVICE =====

    """

    def SubmitGlobalJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchNextSubJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSubJobResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveSubJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKJobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGlobalJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGlobalJob,
                    request_deserializer=zkservice__pb2.GlobalJobRequest.FromString,
                    response_serializer=zkservice__pb2.JobIDResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=zkservice__pb2.JobIDRequest.FromString,
                    response_serializer=zkservice__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetJobSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobSummary,
                    request_deserializer=zkservice__pb2.JobIDRequest.FromString,
                    response_serializer=zkservice__pb2.JobSummaryResponse.SerializeToString,
            ),
            'FetchNextSubJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchNextSubJob,
                    request_deserializer=zkservice__pb2.WorkerIDRequest.FromString,
                    response_serializer=zkservice__pb2.SubJobResponse.SerializeToString,
            ),
            'SubmitSubJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSubJobResult,
                    request_deserializer=zkservice__pb2.SubJobResult.FromString,
                    response_serializer=zkservice__pb2.StatusAck.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=zkservice__pb2.HeartbeatRequest.FromString,
                    response_serializer=zkservice__pb2.HeartbeatAck.SerializeToString,
            ),
            'ListActiveSubJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveSubJobs,
                    request_deserializer=zkservice__pb2.StatusAck.FromString,
                    response_serializer=zkservice__pb2.SubJobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zkservice.ZKJobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zkservice.ZKJobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZKJobService(object):
    """===== SERVICE =====

    """

    @staticmethod
    def SubmitGlobalJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitGlobalJob',
            zkservice__pb2.GlobalJobRequest.SerializeToString,
            zkservice__pb2.JobIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/GetJobStatus',
            zkservice__pb2.JobIDRequest.SerializeToString,
            zkservice__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/GetJobSummary',
            zkservice__pb2.JobIDRequest.SerializeToString,
            zkservice__pb2.JobSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchNextSubJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/FetchNextSubJob',
            zkservice__pb2.WorkerIDRequest.SerializeToString,
            zkservice__pb2.SubJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSubJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitSubJobResult',
            zkservice__pb2.SubJobResult.SerializeToString,
            zkservice__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SendHeartbeat',
            zkservice__pb2.HeartbeatRequest.SerializeToString,
            zkservice__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveSubJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/ListActiveSubJobs',
            zkservice__pb2.StatusAck.SerializeToString,
            zkservice__pb2.SubJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
