syntax = "proto3";


service ZKMLProverDispatcher {
  rpc SubmitJob (JobRequest) returns (JobResponse);
  rpc RegisterWorker (WorkerInfo) returns (WorkerAck);
}

service Worker {
  rpc ComputeProof (JobRequest) returns (JobResponse);
  rpc Ping (Message) returns (MessageResponse);
  rpc CheckProofStatus (ProofStatusRequest) returns (ProofStatusResponse);
}



// The request message containing the onnx model (as bytes) and input data.
message ProofRequest {
  string model_id = 1;  // Unique ID for the model
  bytes onnx_model = 2;  // The ONNX model as bytes
  string input_data = 3;  // The input data as a JSON string
  bool cache_setup_files= 4;  // Whether to cache the setup files
}

message ProofStatusRequest {
    string request_id = 1;  // Unique ID for the request
}


message ProofStatusResponse {
    bool is_completed = 1;
    bool is_success = 2;
    bytes proof = 3;
    string performance_data = 4;
    string message = 5;     // Status message (e.g., "Processing" or "Completed")
}


// The response message containing the computed proof and success status.
message ProofResponse {
    string request_id = 1;  // Unique ID for the request
    string message = 2;     // Status message (e.g., "Request received")
}

// A simple message containing a text message.
message Message {
  string message = 1;
}

// The response message for the Ping method.
message MessageResponse {
  string message = 1;
  bool received = 2;
}