# -*- coding: utf-8 -*-
"""proof_splitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/zkonduit/ezkl/blob/main/examples/notebooks/proof_splitting.ipynb

# Proof splitting

Here we showcase how to split a larger circuit into multiple smaller proofs. This is useful if you want to prove over multiple machines, or if you want to split a proof into multiple parts to reduce the memory requirements.

We showcase how to do this in the case where:
- intermediate calculations can be public (i.e. they do not need to be kept secret) and we can stitch the circuits together using instances
- intermediate calculations need to be kept secret (but not blinded !)  and we need to use the low overhead kzg commitment scheme detailed [here](https://blog.ezkl.xyz/post/commits/) to stitch the circuits together.

First we import the necessary dependencies and set up logging to be as informative as possible.
"""

# Check if running in Colab and install necessary dependencies
try:
    import google.colab
    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ezkl"])
    subprocess.check_call([sys.executable, "-m", "pip", "install", "onnx"])
except ImportError:
    pass

import os
import json
import logging
import torch
import ezkl
from torch import nn
import asyncio
import onnxruntime as ort
import numpy as np
# Uncomment for more descriptive logging
# FORMAT = '%(levelname)s %(name)s %(asctime)-15s %(filename)s:%(lineno)d %(message)s'
# logging.basicConfig(format=FORMAT)
# logging.getLogger().setLevel(logging.INFO)

def load_json_input(file_path):
    """Load input data from a JSON file."""
    with open(file_path, "r") as f:
        return json.load(f)  # Expecting a nested list from np.array().tolist()
    

output_folder = "tests/splt_model"
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
# Export the model to ONNX format
model_path = os.path.join(output_folder,'network.onnx')
data_path = os.path.join(output_folder,  "input_0.json")


# # Define a simple CNN model for demonstration
# class MyModel(nn.Module):
#     def __init__(self):
#         super(MyModel, self).__init__()
#         self.conv1 = nn.Conv2d(in_channels=3, out_channels=8, kernel_size=3, stride=2)
#         self.conv2 = nn.Conv2d(in_channels=8, out_channels=4, kernel_size=3, stride=2)
#         self.relu = nn.ReLU()

#     def forward(self, x):
#         x = self.conv1(x)
#         x = self.relu(x)
#         x = self.conv2(x)
#         x = self.relu(x)
#         return x

#     def split_1(self, x):
#         x = self.conv1(x)
#         x = self.relu(x)
#         return x

# # Instantiate the model
# circuit = MyModel()

# # Simulate random input
# torch.manual_seed(42)  # Set a fixed seed
# # x = torch.rand(1, 3, 8, 8, requires_grad=True)
# x = torch.rand(1, *[3, 8, 8], requires_grad=True)

# #content hash of x tensor
# print(f'model_input:{x}, shape: {x.shape}')

# # splt_1_output = circuit.split_1(x)
# # print(f'split 1 output:{splt_1_output}, shape: {splt_1_output.shape}')


# model_output = circuit(x)
# print(f'global mode output:{model_output}, shape: {model_output.shape}')




# # Set the model to evaluation mode
# circuit.eval()

#run inferecne on model

def format_model_input(input_data_path, expected_shape, input_type, idx = 0):
    expected_shape = [-1 if dim == 'batch_size' else dim for dim in expected_shape]
    input_data = load_json_input(input_data_path)['input_data']
    
    if input_type == 'tensor(float)':
        input_data = np.array(input_data, dtype=np.float32)  # Convert back to NumPy array
        reshaped_input = input_data.reshape(expected_shape)
    
    elif input_type == 'tensor(int64)':
        if len(expected_shape)>0:
            reshaped_input = np.array(input_data[idx], dtype=np.int64)
        else:
            reshaped_input = np.array(input_data[0][0],dtype=np.int64) 
    
    if 'gpt' in str(input_data_path).lower():
        reshaped_input = np.reshape(input_data, (1, 64))  # Shape: (1, 64)

    #import matplotlib.pyplot as plt
    # plt.imshow(reshaped_input.squeeze(), cmap='gray')  # Removes batch and channel dimensions
    # plt.title("Input Image")
    # plt.axis("off")
    # plt.show()
    return reshaped_input

session = ort.InferenceSession(model_path)
# Ensure input matches ONNX model requirements
input_name = session.get_inputs()[0].name
input_shape = session.get_inputs()[0].shape
input_type = session.get_inputs()[0].type
input_tensor = format_model_input(data_path, input_shape, input_type)
# Run inference
outputs = session.run(None, {input_name: input_tensor})

print(f'onnx model inference output: {outputs}')

# torch.onnx.export(circuit, x, model_path, export_params=True, opset_version=10, do_constant_folding=True, 
#                   input_names=['input'], output_names=['output'], dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}})

# Create a corresponding random input JSON file for the model
data_path = os.path.join(output_folder,  "input_0.json")
# data = dict(input_data=[(x.detach().numpy()).reshape([-1]).tolist()])
# json.dump(data, open(data_path, 'w'))

# Perform a split on the model
# inter_1 = circuit.split_1(x)
data_path = os.path.join(output_folder, "input_1.json")
# data = dict(input_data=[(inter_1.detach().numpy()).reshape([-1]).tolist()])
# json.dump(data, open(data_path, 'w'))

# Split the model into two parts and create ONNX files for each part
# import onnx
# onnx.utils.extract_model(model_path, os.path.join(output_folder,"network_split_0.onnx"), input_names=["input"], output_names=["/relu/Relu_output_0"])
# onnx.utils.extract_model(model_path, os.path.join(output_folder,"network_split_1.onnx"), input_names=["/relu/Relu_output_0"], output_names=["output"])

# # Setup EZKL run parameters for public intermediate calculations
# run_args = ezkl.PyRunArgs()
# run_args.input_visibility = "polycommit"
# run_args.param_visibility = "fixed"
# run_args.output_visibility = "polycommit"
# run_args.input_scale = 2
# run_args.logrows = 15

# Setup EZKL run parameters for public intermediate calculations
run_args = ezkl.PyRunArgs()
run_args.input_visibility = "public"
run_args.param_visibility = "fixed"
run_args.output_visibility = "public"
run_args.input_scale = 2
run_args.logrows = 15


# Generate SRS for KZG commitment
ezkl.get_srs(logrows=run_args.logrows, commitment=ezkl.PyCommitments.KZG)


# Function to set up and calibrate the model for zkSNARK
def setup(i):

    model_path = os.path.join(output_folder,'network_split_' + str(i) + '.onnx')
    settings_path = os.path.join(output_folder,'settings_split_' + str(i) + '.json')
    data_path = os.path.join(output_folder,'input_' + str(i) + '.json')
    compiled_model_path = os.path.join(output_folder,'network_split_' + str(i) + '.compiled')
    pk_path = os.path.join(output_folder,'test_split_' + str(i) + '.pk')
    vk_path = os.path.join(output_folder,'test_split_' + str(i) + '.vk')
    witness_path = os.path.join(output_folder,'witness_split_' + str(i) + '.json')

    # For non-first models, use previous witness data
    if i > 0:
        prev_witness_path = os.path.join(output_folder,'witness_split_' + str(i - 1) + '.json')
        witness = json.load(open(prev_witness_path, 'r'))
        data = dict(input_data=witness['outputs'])
        json.dump(data, open(data_path, 'w'))
    else:
        data_path = os.path.join(output_folder,'input_0.json')

    # Generate settings for the current model
    res = ezkl.gen_settings(model_path, settings_path, py_run_args=run_args)
    res = ezkl.calibrate_settings(data_path, model_path, settings_path, "resources", scales=[run_args.input_scale], max_logrows=run_args.logrows)
    assert res == True

    # Load settings and save back to file
    settings = json.load(open(settings_path, 'r'))
    settings['run_args']['logrows'] = run_args.logrows
    json.dump(settings, open(settings_path, 'w'))

    # Compile the circuit
    res = ezkl.compile_circuit(model_path, compiled_model_path, settings_path)
    res = ezkl.setup(compiled_model_path, vk_path, pk_path)
    assert res == True
    assert os.path.isfile(vk_path)
    assert os.path.isfile(pk_path)

    # Generate the witness
    res = ezkl.gen_witness(data_path, compiled_model_path, witness_path, vk_path)
    run_args.input_scale = settings["model_output_scales"][0]

# Async function to run multiple setups
def run_setups():
    for i in range(2):  # Adjust the range as needed for the number of models
         setup(i)

# Run the async function
run_setups()

# Generate and verify proof
def prove_model(i):
    proof_path = os.path.join(output_folder,'proof_split_' + str(i) + '.json')
    witness_path = os.path.join(output_folder,'witness_split_' + str(i) + '.json')
    compiled_model_path = os.path.join(output_folder,'network_split_' + str(i) + '.compiled')
    pk_path = os.path.join(output_folder,'test_split_' + str(i) + '.pk')
    vk_path = os.path.join(output_folder,'test_split_' + str(i) + '.vk')
    settings_path = os.path.join(output_folder,'settings_split_' + str(i) + '.json')

    res = ezkl.prove(witness_path, compiled_model_path, pk_path, proof_path, "for-aggr")
    print(res)

    # Swap commitments for subsequent models
    if i > 0:
        print("swapping commitments")
        prev_witness_path = os.path.join(output_folder,'witness_split_' + str(i - 1) + '.json')
        prev_witness = json.load(open(prev_witness_path, 'r'))
        witness = json.load(open(witness_path, 'r'))

        print(prev_witness["processed_outputs"])
        print(witness["processed_inputs"])
        witness["processed_inputs"] = prev_witness["processed_outputs"]

        # Save the modified witness
        with open(witness_path, "w") as f:
            json.dump(witness, f)

        res = ezkl.swap_proof_commitments(proof_path, witness_path)
        print(res)

    # Verify the proof
    res = ezkl.verify(proof_path, settings_path, vk_path)
    assert res == True
    print("verified")

# Loop over models to prove
for i in range(2):
    prove_model(i)

# # KZG commitment intermediate calculations (polycommit visibility)
# run_args.input_visibility = "polycommit"
# run_args.output_visibility = "polycommit"
