# config/config.yaml

defaults:
  - _self_
  - backend: ezkl
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
coordinator:
  host: localhost
  port: 50051
  grpc_thread_pool_size: 4
  grpc_max_message_mb: 64
  runs_dir: experiments/runs
  logs_dir: logs/coordinator

worker:
  worker_id: null
  runs_dir: experiments/runs
  logs_dir: logs/workers
  job_poll_interval_sec: 5
  resource_monitor_interval_sec: 3
  send_proofs_to_coordinator: true

jobs:
  scheduler: fifo
  max_retries: 0

heartbeat:
  interval_sec: 5
  timeout_sec: 45

storage:
  backend: filesystem # filesystem | s3

  # Shared storage for coordinator <-> worker communication.
  transfer_prefix: storage/transfer

  # Shared persistent proving cache.
  proving_cache_enabled: false
  proving_cache_prefix: storage/cache
  proving_cache_overwrite: false

  # Used only when backend=s3.
  s3_bucket: null
  s3_prefix: zkinfer

hydra:
  run:
    dir: .

  sweep:
    dir: .

  output_subdir: null

  job_logging:
    level: DISABLE

  hydra_logging:
    level: DISABLE