# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zkservice.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'zkservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzkservice.proto\x12\tzkservice\"}\n\x10InferenceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fonnx_model_path\x18\x02 \x01(\t\x12\x17\n\x0finput_data_path\x18\x03 \x01(\t\x12\x12\n\nsplit_mode\x18\x04 \x01(\t\x12\x15\n\rops_per_chunk\x18\x05 \x01(\x05\"1\n\x1bInferenceSubmissionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"$\n\x0fWorkerIdRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x9f\x01\n\rJobAssignment\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x12\n\ninput_json\x18\x03 \x01(\t\x12\x11\n\ts3_bucket\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61\x63he_setup\x18\x05 \x01(\x08\x12\x17\n\x0foverwrite_setup\x18\x06 \x01(\x08\x12\x15\n\rjob_available\x18\x07 \x01(\x08\"r\n\tJobResult\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05proof\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\tezkl_json\x18\x04 \x01(\t\x12\x12\n\nhalo2_json\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\"\\\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\x1f\n\x0cHeartbeatAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\tStatusAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb7\x02\n\x0cZKJobService\x12]\n\x16SubmitInferenceRequest\x12\x1b.zkservice.InferenceRequest\x1a&.zkservice.InferenceSubmissionResponse\x12\x42\n\nGetNextJob\x12\x1a.zkservice.WorkerIdRequest\x1a\x18.zkservice.JobAssignment\x12=\n\x0fSubmitJobResult\x12\x14.zkservice.JobResult\x1a\x14.zkservice.StatusAck\x12\x45\n\rSendHeartbeat\x12\x1b.zkservice.HeartbeatRequest\x1a\x17.zkservice.HeartbeatAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=155
  _globals['_INFERENCESUBMISSIONRESPONSE']._serialized_start=157
  _globals['_INFERENCESUBMISSIONRESPONSE']._serialized_end=206
  _globals['_WORKERIDREQUEST']._serialized_start=208
  _globals['_WORKERIDREQUEST']._serialized_end=244
  _globals['_JOBASSIGNMENT']._serialized_start=247
  _globals['_JOBASSIGNMENT']._serialized_end=406
  _globals['_JOBRESULT']._serialized_start=408
  _globals['_JOBRESULT']._serialized_end=522
  _globals['_HEARTBEATREQUEST']._serialized_start=524
  _globals['_HEARTBEATREQUEST']._serialized_end=616
  _globals['_HEARTBEATACK']._serialized_start=618
  _globals['_HEARTBEATACK']._serialized_end=649
  _globals['_STATUSACK']._serialized_start=651
  _globals['_STATUSACK']._serialized_end=696
  _globals['_ZKJOBSERVICE']._serialized_start=699
  _globals['_ZKJOBSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
