syntax = "proto3";

package zkservice;

/*
python -m grpc_tools.protoc -IzkInfer --python_out=zkInfer --grpc_python_out=zkInfer zkInfer/zkservice.proto
*/

// ===== ENUMS =====

/*
enum SubJobStatus {
  UNKNOWN = 0;
  QUEUED = 1;
  STARTED = 2;
  GENERATING_SETTINGS = 3;
  CALIBRATING = 4;
  COMPILING = 5;
  SETTING_UP = 6;
  PROVING = 7;
  VERIFYING = 8;
  DONE = 9;
  FAILED = 10;
} */

// ===== USER SUBMISSION & JOB STATUS =====

message InferenceRequest {
  string name = 1;
  string onnx_model_path = 2;
  string input_data_path = 3;
  string split_mode = 4;          // "none", "auto", or "fixed"
  int32 ops_per_chunk = 5;        // Only used if split_mode == "fixed"
}

message InferenceSubmissionResponse {
  string request_id = 1;
}

// ===== WORKER INTERACTION =====
message WorkerIdRequest {
  string worker_id = 1;
}

// JobAssignment: Information needed by the worker to process a job.
message JobAssignment {
  string job_id = 1;
  string model_path = 2;
  string input_json = 3;
  string s3_bucket = 4; // Only used if storage_backend == "s3"
  bool cache_setup = 5; // Whether to keep model artifacts (model files, etc.)
  bool overwrite_setup = 6; // Whether to overwrite existing files
  bool job_available = 7; // Indicates if the job is still available
}

// The result of a job proof computation.
message JobResult {
  string job_id = 1;
  bytes proof = 2;
  string status = 3;
  string perf_metrics = 4;
  string message = 5; // Additional message or error description
}

// ===== HEARTBEAT & STATUS =====

message HeartbeatRequest {
  string worker_id = 1;
  string job_id = 2;
  string status = 3;
  string error_message = 4;
}
message HeartbeatAck {
  bool success = 1;
}

message StatusAck {
  bool success = 1;
  string message = 2;
}

// ===== SERVICE =====

service ZKJobService {

  // User API
  rpc SubmitInferenceRequest (InferenceRequest) returns (InferenceSubmissionResponse);
  //rpc GetJobStatus (JobIDRequest) returns (JobStatusResponse);
  //rpc GetJobSummary (JobIDRequest) returns (JobSummaryResponse);

  // Worker API
  rpc GetNextJob (WorkerIdRequest) returns (JobAssignment);
  rpc SubmitJobResult (JobResult) returns (StatusAck);

  // Heartbeats and Monitoring
  rpc SendHeartbeat (HeartbeatRequest) returns (HeartbeatAck);

  // Performance reporting
  //rpc SendPerfReport (PerfReport) returns (StatusAck);

}
