# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zkservice_pb2 as zkservice__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zkservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZKJobServiceStub(object):
    """===== SERVICE =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitJob',
                request_serializer=zkservice__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobSubmissionResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/zkservice.ZKJobService/GetJobStatus',
                request_serializer=zkservice__pb2.JobIDRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.GetNextSubJob = channel.unary_unary(
                '/zkservice.ZKJobService/GetNextSubJob',
                request_serializer=zkservice__pb2.WorkerIDRequest.SerializeToString,
                response_deserializer=zkservice__pb2.SubJobAssignment.FromString,
                _registered_method=True)
        self.SubmitSubJobResult = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitSubJobResult',
                request_serializer=zkservice__pb2.SubJobResult.SerializeToString,
                response_deserializer=zkservice__pb2.StatusAck.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/zkservice.ZKJobService/SendHeartbeat',
                request_serializer=zkservice__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=zkservice__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.SendPerfReport = channel.unary_unary(
                '/zkservice.ZKJobService/SendPerfReport',
                request_serializer=zkservice__pb2.PerfReport.SerializeToString,
                response_deserializer=zkservice__pb2.StatusAck.FromString,
                _registered_method=True)


class ZKJobServiceServicer(object):
    """===== SERVICE =====

    """

    def SubmitJob(self, request, context):
        """User API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """rpc GetJobSummary (JobIDRequest) returns (JobSummaryResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextSubJob(self, request, context):
        """Worker API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSubJobResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Heartbeats and Monitoring
        rpc ListActiveSubJobs (StatusAck) returns (SubJobStatusResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPerfReport(self, request, context):
        """Performance reporting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKJobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=zkservice__pb2.SubmitJobRequest.FromString,
                    response_serializer=zkservice__pb2.JobSubmissionResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=zkservice__pb2.JobIDRequest.FromString,
                    response_serializer=zkservice__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetNextSubJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextSubJob,
                    request_deserializer=zkservice__pb2.WorkerIDRequest.FromString,
                    response_serializer=zkservice__pb2.SubJobAssignment.SerializeToString,
            ),
            'SubmitSubJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSubJobResult,
                    request_deserializer=zkservice__pb2.SubJobResult.FromString,
                    response_serializer=zkservice__pb2.StatusAck.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=zkservice__pb2.HeartbeatRequest.FromString,
                    response_serializer=zkservice__pb2.HeartbeatAck.SerializeToString,
            ),
            'SendPerfReport': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPerfReport,
                    request_deserializer=zkservice__pb2.PerfReport.FromString,
                    response_serializer=zkservice__pb2.StatusAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zkservice.ZKJobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zkservice.ZKJobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZKJobService(object):
    """===== SERVICE =====

    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitJob',
            zkservice__pb2.SubmitJobRequest.SerializeToString,
            zkservice__pb2.JobSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/GetJobStatus',
            zkservice__pb2.JobIDRequest.SerializeToString,
            zkservice__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextSubJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/GetNextSubJob',
            zkservice__pb2.WorkerIDRequest.SerializeToString,
            zkservice__pb2.SubJobAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSubJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitSubJobResult',
            zkservice__pb2.SubJobResult.SerializeToString,
            zkservice__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SendHeartbeat',
            zkservice__pb2.HeartbeatRequest.SerializeToString,
            zkservice__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPerfReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SendPerfReport',
            zkservice__pb2.PerfReport.SerializeToString,
            zkservice__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
