# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zkservice_pb2 as zkservice__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zkservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZKJobServiceStub(object):
    """===== SERVICE =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitInferenceRequest = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitInferenceRequest',
                request_serializer=zkservice__pb2.InferenceRequest.SerializeToString,
                response_deserializer=zkservice__pb2.InferenceSubmissionResponse.FromString,
                _registered_method=True)
        self.GetNextJob = channel.unary_unary(
                '/zkservice.ZKJobService/GetNextJob',
                request_serializer=zkservice__pb2.WorkerIdRequest.SerializeToString,
                response_deserializer=zkservice__pb2.JobAssignment.FromString,
                _registered_method=True)
        self.SubmitJobResult = channel.unary_unary(
                '/zkservice.ZKJobService/SubmitJobResult',
                request_serializer=zkservice__pb2.JobResult.SerializeToString,
                response_deserializer=zkservice__pb2.StatusAck.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/zkservice.ZKJobService/SendHeartbeat',
                request_serializer=zkservice__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=zkservice__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class ZKJobServiceServicer(object):
    """===== SERVICE =====

    """

    def SubmitInferenceRequest(self, request, context):
        """User API
        rpc GetJobStatus (JobIDRequest) returns (JobStatusResponse);
        rpc GetJobSummary (JobIDRequest) returns (JobSummaryResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextJob(self, request, context):
        """Worker API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJobResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Heartbeats and Monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKJobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitInferenceRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInferenceRequest,
                    request_deserializer=zkservice__pb2.InferenceRequest.FromString,
                    response_serializer=zkservice__pb2.InferenceSubmissionResponse.SerializeToString,
            ),
            'GetNextJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextJob,
                    request_deserializer=zkservice__pb2.WorkerIdRequest.FromString,
                    response_serializer=zkservice__pb2.JobAssignment.SerializeToString,
            ),
            'SubmitJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJobResult,
                    request_deserializer=zkservice__pb2.JobResult.FromString,
                    response_serializer=zkservice__pb2.StatusAck.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=zkservice__pb2.HeartbeatRequest.FromString,
                    response_serializer=zkservice__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zkservice.ZKJobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zkservice.ZKJobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZKJobService(object):
    """===== SERVICE =====

    """

    @staticmethod
    def SubmitInferenceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitInferenceRequest',
            zkservice__pb2.InferenceRequest.SerializeToString,
            zkservice__pb2.InferenceSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/GetNextJob',
            zkservice__pb2.WorkerIdRequest.SerializeToString,
            zkservice__pb2.JobAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SubmitJobResult',
            zkservice__pb2.JobResult.SerializeToString,
            zkservice__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zkservice.ZKJobService/SendHeartbeat',
            zkservice__pb2.HeartbeatRequest.SerializeToString,
            zkservice__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
